export const CLAUDE_TOKEN_HEADER = "x-session-runtime-claude-token";
export const SESSION_RUNTIME_CLI_INPUT_B64_ENV = "SESSION_RUNTIME_API_INPUT_B64";
export const SESSION_RUNTIME_CLI_CLAUDE_TOKEN_ENV = "SESSION_RUNTIME_CLAUDE_TOKEN";
