// This file is auto-generated by gqlkit. DO NOT EDIT.

import { GraphQLScalarType } from "graphql";
import {
  agentMessageEventDataResolveType as AgentMessageEventData$__resolveType,
  agentMessagePartResolveType as AgentMessagePart$__resolveType,
} from "../schema/agent-message";
import {
  sendSessionChatMessage as Mutation$sendSessionChatMessage,
  submitSessionChatUserInput as Mutation$submitSessionChatUserInput,
  chat as Session$chat,
  pendingUserInput as SessionChat$pendingUserInput,
  sessionChatPendingRequestResolveType as SessionChatPendingRequest$__resolveType,
  sessionChatPendingUserInputPayloadResolveType as SessionChatPendingUserInputPayload$__resolveType,
} from "../schema/session-chat";
import {
  createSession as Mutation$createSession,
  executeSession as Mutation$executeSession,
  terminateSession as Mutation$terminateSession,
  session as Query$session,
  sessions as Query$sessions,
  ssh as Session$ssh,
} from "../schema/session";
import {
  saveClaudeApiKey as Mutation$saveClaudeApiKey,
  viewer as Query$viewer,
} from "../schema/viewer";
import type { DateTime, JsonValue } from "../schema/scalars";

export function createResolvers({
  scalars,
}: {
  scalars: {
    DateTime: GraphQLScalarType<DateTime, DateTime>;
    JSON: GraphQLScalarType<JsonValue, JsonValue>;
  };
}) {
  return {
    AgentMessageMetadataVisibility: {
      DEFAULT: "default",
      TRACE: "trace",
    },
    AgentMessageMetadataStatus: {
      ERROR: "error",
      IN_PROGRESS: "in-progress",
      DONE: "done",
    },
    AgentMessageTextPartState: {
      DONE: "done",
      STREAMING: "streaming",
    },
    AgentMessageReasoningPartState: {
      DONE: "done",
      STREAMING: "streaming",
    },
    AgentMessageDynamicToolPartState: {
      INPUT_STREAMING: "input-streaming",
      INPUT_AVAILABLE: "input-available",
      APPROVAL_REQUESTED: "approval-requested",
      APPROVAL_RESPONDED: "approval-responded",
      OUTPUT_AVAILABLE: "output-available",
      OUTPUT_ERROR: "output-error",
      OUTPUT_DENIED: "output-denied",
    },
    SubmitSessionChatUserInputBehaviorInput: {
      ALLOW: "allow",
      DENY: "deny",
    },
    AgentMessageRole: {
      USER: "user",
      ASSISTANT: "assistant",
      SYSTEM: "system",
    },
    AgentMessageProvider: {
      CLAUDE_AGENT_SDK: "claude-agent-sdk",
    },
    AgentMessageEventKind: {
      TOOL_PROGRESS: "tool-progress",
      TOOL_SUMMARY: "tool-summary",
      STATUS: "status",
      FILE_BATCH: "file-batch",
      STREAM: "stream",
      ERROR: "error",
      UNKNOWN: "unknown",
    },
    SessionChatPendingRequestKind: {
      ASK_USER_QUESTION: "ask-user-question",
      TOOL_APPROVAL: "tool-approval",
    },
    SendSessionChatMessageStatus: {
      SUBMITTED: "submitted",
    },
    SessionStatus: {
      ERROR: "error",
      CREATING: "creating",
      RUNNING: "running",
      TERMINATED: "terminated",
    },
    DateTime: scalars.DateTime,
    JSON: scalars.JSON,
    AgentMessageEventData: {
      __resolveType: AgentMessageEventData$__resolveType,
    },
    AgentMessagePart: {
      __resolveType: AgentMessagePart$__resolveType,
    },
    Mutation: {
      createSession: Mutation$createSession,
      executeSession: Mutation$executeSession,
      saveClaudeApiKey: Mutation$saveClaudeApiKey,
      sendSessionChatMessage: Mutation$sendSessionChatMessage,
      submitSessionChatUserInput: Mutation$submitSessionChatUserInput,
      terminateSession: Mutation$terminateSession,
    },
    Query: {
      session: Query$session,
      sessions: Query$sessions,
      viewer: Query$viewer,
    },
    Session: {
      chat: Session$chat,
      ssh: Session$ssh,
    },
    SessionChat: {
      pendingUserInput: SessionChat$pendingUserInput,
    },
    SessionChatPendingRequest: {
      __resolveType: SessionChatPendingRequest$__resolveType,
    },
    SessionChatPendingUserInputPayload: {
      __resolveType: SessionChatPendingUserInputPayload$__resolveType,
    },
  };
}
