// This file is auto-generated by gqlkit. DO NOT EDIT.

import type { GraphQLScalarType } from "graphql";
import type { DateTime, JsonValue } from "../schema/scalars";
import {
  session as Query$session,
  sessions as Query$sessions,
  ssh as Session$ssh,
} from "../schema/session";
import { viewer as Query$viewer } from "../schema/viewer";

export function createResolvers({
  scalars,
}: {
  scalars: {
    DateTime: GraphQLScalarType<DateTime, DateTime>;
    JSON: GraphQLScalarType<JsonValue, JsonValue>;
  };
}) {
  return {
    SessionStatus: {
      CREATING: "creating",
      RUNNING: "running",
      TERMINATED: "terminated",
      ERROR: "error",
    },
    DateTime: scalars.DateTime,
    JSON: scalars.JSON,
    Query: {
      session: Query$session,
      sessions: Query$sessions,
      viewer: Query$viewer,
    },
    Session: {
      ssh: Session$ssh,
    },
  };
}
