// This file is auto-generated by gqlkit. DO NOT EDIT.

import type { DocumentNode } from "graphql";

export const typeDefs: DocumentNode = {
  kind: "Document",
  definitions: [
    {
      kind: "ScalarTypeDefinition",
      name: {
        kind: "Name",
        value: "DateTime",
      },
    },
    {
      kind: "ScalarTypeDefinition",
      name: {
        kind: "Name",
        value: "JSON",
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "AgentMessage",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "id",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "ID",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "metadata",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "AgentMessageMetadata",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "parts",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "ListType",
              type: {
                kind: "NonNullType",
                type: {
                  kind: "NamedType",
                  name: {
                    kind: "Name",
                    value: "AgentMessagePart",
                  },
                },
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "role",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "AgentMessageRole",
              },
            },
          },
          description: {
            kind: "StringValue",
            value: "The role of the message.",
            block: true,
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/agent-message.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "AgentMessageDynamicToolPart",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "approval",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "AgentMessageDynamicToolPartApproval",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "errorText",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "input",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "JSON",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "output",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "JSON",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "preliminary",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "Boolean",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "providerExecuted",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "Boolean",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "state",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "title",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "toolCallId",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "toolName",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "type",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/agent-message.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "AgentMessageDynamicToolPartApproval",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "approved",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "Boolean",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "id",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "reason",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/agent-message.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "AgentMessageErrorEvent",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "code",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "kind",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "message",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/agent-message.ts",
        block: true,
      },
    },
    {
      kind: "UnionTypeDefinition",
      name: {
        kind: "Name",
        value: "AgentMessageEventData",
      },
      types: [
        {
          kind: "NamedType",
          name: {
            kind: "Name",
            value: "AgentMessageErrorEvent",
          },
        },
        {
          kind: "NamedType",
          name: {
            kind: "Name",
            value: "AgentMessageFileBatchEvent",
          },
        },
        {
          kind: "NamedType",
          name: {
            kind: "Name",
            value: "AgentMessageStatusEvent",
          },
        },
        {
          kind: "NamedType",
          name: {
            kind: "Name",
            value: "AgentMessageStreamEvent",
          },
        },
        {
          kind: "NamedType",
          name: {
            kind: "Name",
            value: "AgentMessageToolProgressEvent",
          },
        },
        {
          kind: "NamedType",
          name: {
            kind: "Name",
            value: "AgentMessageToolSummaryEvent",
          },
        },
        {
          kind: "NamedType",
          name: {
            kind: "Name",
            value: "AgentMessageUnknownEvent",
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/agent-message.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "AgentMessageEventPart",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "data",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "AgentMessageEventData",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "type",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/agent-message.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "AgentMessageFileBatchEvent",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "failed",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "ListType",
              type: {
                kind: "NonNullType",
                type: {
                  kind: "NamedType",
                  name: {
                    kind: "Name",
                    value: "AgentMessageFileBatchFailure",
                  },
                },
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "files",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "ListType",
              type: {
                kind: "NonNullType",
                type: {
                  kind: "NamedType",
                  name: {
                    kind: "Name",
                    value: "AgentMessageFileBatchFile",
                  },
                },
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "kind",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "processedAt",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "DateTime",
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/agent-message.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "AgentMessageFileBatchFailure",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "error",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "filename",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/agent-message.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "AgentMessageFileBatchFile",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "fileId",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "filename",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/agent-message.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "AgentMessageMetadata",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "createdAt",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "isReplay",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "Boolean",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "isSynthetic",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "Boolean",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "label",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "parentToolUseId",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "provider",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "AgentMessageMetadataProvider",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "providerMessageType",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "providerSessionId",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "providerSubtype",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "providerUuid",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "rawStoredMessageId",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "status",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "AgentMessageMetadataStatus",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "updatedAt",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "visibility",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "AgentMessageMetadataVisibility",
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/agent-message.ts",
        block: true,
      },
    },
    {
      kind: "EnumTypeDefinition",
      name: {
        kind: "Name",
        value: "AgentMessageMetadataProvider",
      },
      values: [
        {
          kind: "EnumValueDefinition",
          name: {
            kind: "Name",
            value: "CLAUDE_AGENT_SDK",
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/lib/session-chat-types.ts",
        block: true,
      },
    },
    {
      kind: "EnumTypeDefinition",
      name: {
        kind: "Name",
        value: "AgentMessageMetadataStatus",
      },
      values: [
        {
          kind: "EnumValueDefinition",
          name: {
            kind: "Name",
            value: "ERROR",
          },
        },
        {
          kind: "EnumValueDefinition",
          name: {
            kind: "Name",
            value: "IN_PROGRESS",
          },
        },
        {
          kind: "EnumValueDefinition",
          name: {
            kind: "Name",
            value: "DONE",
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/lib/session-chat-types.ts",
        block: true,
      },
    },
    {
      kind: "EnumTypeDefinition",
      name: {
        kind: "Name",
        value: "AgentMessageMetadataVisibility",
      },
      values: [
        {
          kind: "EnumValueDefinition",
          name: {
            kind: "Name",
            value: "DEFAULT",
          },
        },
        {
          kind: "EnumValueDefinition",
          name: {
            kind: "Name",
            value: "TRACE",
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/lib/session-chat-types.ts",
        block: true,
      },
    },
    {
      kind: "UnionTypeDefinition",
      name: {
        kind: "Name",
        value: "AgentMessagePart",
      },
      types: [
        {
          kind: "NamedType",
          name: {
            kind: "Name",
            value: "AgentMessageDynamicToolPart",
          },
        },
        {
          kind: "NamedType",
          name: {
            kind: "Name",
            value: "AgentMessageEventPart",
          },
        },
        {
          kind: "NamedType",
          name: {
            kind: "Name",
            value: "AgentMessageReasoningPart",
          },
        },
        {
          kind: "NamedType",
          name: {
            kind: "Name",
            value: "AgentMessageResultPart",
          },
        },
        {
          kind: "NamedType",
          name: {
            kind: "Name",
            value: "AgentMessageTextPart",
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/agent-message.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "AgentMessageReasoningPart",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "state",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "text",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "type",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/agent-message.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "AgentMessageResultData",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "isError",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "Boolean",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "metrics",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "AgentMessageResultDataMetrics",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "subtype",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "summaryText",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/agent-message.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "AgentMessageResultDataMetrics",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "durationApiMs",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "Float",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "durationMs",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "Float",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "numTurns",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "Float",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "totalCostUsd",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "Float",
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/lib/session-chat-types.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "AgentMessageResultMetrics",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "durationApiMs",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "Float",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "durationMs",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "Float",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "numTurns",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "Float",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "totalCostUsd",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "Float",
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/agent-message.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "AgentMessageResultPart",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "data",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "AgentMessageResultPartData",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "type",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/agent-message.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "AgentMessageResultPartData",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "isError",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "Boolean",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "metrics",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "AgentMessageResultPartDataMetrics",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "subtype",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "summaryText",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/agent-message.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "AgentMessageResultPartDataMetrics",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "durationApiMs",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "Float",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "durationMs",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "Float",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "numTurns",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "Float",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "totalCostUsd",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "Float",
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/lib/session-chat-types.ts",
        block: true,
      },
    },
    {
      kind: "EnumTypeDefinition",
      name: {
        kind: "Name",
        value: "AgentMessageRole",
      },
      values: [
        {
          kind: "EnumValueDefinition",
          name: {
            kind: "Name",
            value: "SYSTEM",
          },
        },
        {
          kind: "EnumValueDefinition",
          name: {
            kind: "Name",
            value: "USER",
          },
        },
        {
          kind: "EnumValueDefinition",
          name: {
            kind: "Name",
            value: "ASSISTANT",
          },
        },
      ],
      description: {
        kind: "StringValue",
        value:
          "Defined in: ../../node_modules/.pnpm/ai@6.0.97_zod@4.3.6/node_modules/ai/dist/index.d.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "AgentMessageStatusEvent",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "data",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "JSON",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "kind",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "subtype",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/agent-message.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "AgentMessageStreamEvent",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "data",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "JSON",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "eventType",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "kind",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/agent-message.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "AgentMessageTextPart",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "state",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "text",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "type",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/agent-message.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "AgentMessageToolProgressEvent",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "elapsedSeconds",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "Float",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "kind",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "toolName",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "toolUseId",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/agent-message.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "AgentMessageToolSummaryEvent",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "kind",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "precedingToolUseIds",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "ListType",
              type: {
                kind: "NonNullType",
                type: {
                  kind: "NamedType",
                  name: {
                    kind: "Name",
                    value: "String",
                  },
                },
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "summary",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/agent-message.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "AgentMessageUnknownEvent",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "data",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "JSON",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "kind",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "rawSubtype",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "rawType",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/agent-message.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "AuthUser",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "github",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "GithubAccount",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "id",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "ID",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/viewer.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "GithubAccount",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "avatarUrl",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "email",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "id",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "ID",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "login",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "name",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/viewer.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "Mutation",
      },
      fields: [],
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "Query",
      },
      fields: [],
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "SaveClaudeApiKeyPayload",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "claudeApiKeyConfigured",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "Boolean",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/viewer.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "SendSessionChatMessagePayload",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "status",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "SendSessionChatMessageStatus",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/session-chat.ts",
        block: true,
      },
    },
    {
      kind: "EnumTypeDefinition",
      name: {
        kind: "Name",
        value: "SendSessionChatMessageStatus",
      },
      values: [
        {
          kind: "EnumValueDefinition",
          name: {
            kind: "Name",
            value: "SUBMITTED",
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/session-chat.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "Session",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "createdAt",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "DateTime",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "id",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "ID",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "lastError",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "name",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "repoRef",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "repoUrl",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "status",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "SessionStatus",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "updatedAt",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "DateTime",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "workspacePath",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/session.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "SessionChat",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "messages",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "ListType",
              type: {
                kind: "NonNullType",
                type: {
                  kind: "NamedType",
                  name: {
                    kind: "Name",
                    value: "AgentMessage",
                  },
                },
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "rawCount",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "Int",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "thread",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "SessionChatThread",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/session-chat.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "SessionChatAskUserQuestionPendingRequest",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "agentId",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "blockedPath",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "createdAt",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "DateTime",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "decisionReason",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "input",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "JSON",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "kind",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "SessionChatPendingRequestKind",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "questions",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "ListType",
              type: {
                kind: "NonNullType",
                type: {
                  kind: "NamedType",
                  name: {
                    kind: "Name",
                    value: "SessionChatPendingUserInputQuestion",
                  },
                },
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "requestId",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "suggestions",
          },
          type: {
            kind: "ListType",
            type: {
              kind: "NonNullType",
              type: {
                kind: "NamedType",
                name: {
                  kind: "Name",
                  value: "JSON",
                },
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "toolName",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "toolUseId",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/session-chat.ts",
        block: true,
      },
    },
    {
      kind: "UnionTypeDefinition",
      name: {
        kind: "Name",
        value: "SessionChatPendingRequest",
      },
      types: [
        {
          kind: "NamedType",
          name: {
            kind: "Name",
            value: "SessionChatAskUserQuestionPendingRequest",
          },
        },
        {
          kind: "NamedType",
          name: {
            kind: "Name",
            value: "SessionChatToolApprovalPendingRequest",
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/session-chat.ts",
        block: true,
      },
    },
    {
      kind: "EnumTypeDefinition",
      name: {
        kind: "Name",
        value: "SessionChatPendingRequestKind",
      },
      values: [
        {
          kind: "EnumValueDefinition",
          name: {
            kind: "Name",
            value: "ASK_USER_QUESTION",
          },
        },
        {
          kind: "EnumValueDefinition",
          name: {
            kind: "Name",
            value: "TOOL_APPROVAL",
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/session-chat.ts",
        block: true,
      },
    },
    {
      kind: "UnionTypeDefinition",
      name: {
        kind: "Name",
        value: "SessionChatPendingUserInputPayload",
      },
      types: [
        {
          kind: "NamedType",
          name: {
            kind: "Name",
            value: "SessionChatAskUserQuestionPendingRequest",
          },
        },
        {
          kind: "NamedType",
          name: {
            kind: "Name",
            value: "SessionChatToolApprovalPendingRequest",
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/session-chat.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "SessionChatPendingUserInputQuestion",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "header",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "multiSelect",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "Boolean",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "options",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "ListType",
              type: {
                kind: "NonNullType",
                type: {
                  kind: "NamedType",
                  name: {
                    kind: "Name",
                    value: "SessionChatPendingUserInputQuestionOption",
                  },
                },
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "question",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/session-chat.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "SessionChatPendingUserInputQuestionOption",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "description",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "label",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/session-chat.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "SessionChatThread",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "claudeSdkSessionId",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "createdAt",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "DateTime",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "cwd",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "id",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "ID",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "isRunning",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "Boolean",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "lastError",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "maxTurns",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "Int",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "sessionId",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "ID",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "updatedAt",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "DateTime",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/session-chat.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "SessionChatToolApprovalPendingRequest",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "agentId",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "blockedPath",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "createdAt",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "DateTime",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "decisionReason",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "input",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "JSON",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "kind",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "SessionChatPendingRequestKind",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "requestId",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "suggestions",
          },
          type: {
            kind: "ListType",
            type: {
              kind: "NonNullType",
              type: {
                kind: "NamedType",
                name: {
                  kind: "Name",
                  value: "JSON",
                },
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "toolName",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "toolUseId",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/session-chat.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "SessionExecResult",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "exitCode",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "Int",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "stderr",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "stdout",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/session.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "SessionSshInfo",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "command",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "host",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "hostKeyFingerprint",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "knownHostsEntry",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "port",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "Int",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "user",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/session.ts",
        block: true,
      },
    },
    {
      kind: "EnumTypeDefinition",
      name: {
        kind: "Name",
        value: "SessionStatus",
      },
      values: [
        {
          kind: "EnumValueDefinition",
          name: {
            kind: "Name",
            value: "CREATING",
          },
        },
        {
          kind: "EnumValueDefinition",
          name: {
            kind: "Name",
            value: "RUNNING",
          },
        },
        {
          kind: "EnumValueDefinition",
          name: {
            kind: "Name",
            value: "TERMINATED",
          },
        },
        {
          kind: "EnumValueDefinition",
          name: {
            kind: "Name",
            value: "ERROR",
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/session.ts",
        block: true,
      },
    },
    {
      kind: "EnumTypeDefinition",
      name: {
        kind: "Name",
        value: "SubmitSessionChatUserInputBehaviorInput",
      },
      values: [
        {
          kind: "EnumValueDefinition",
          name: {
            kind: "Name",
            value: "ALLOW",
          },
        },
        {
          kind: "EnumValueDefinition",
          name: {
            kind: "Name",
            value: "DENY",
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/session-chat.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "SubmitSessionChatUserInputPayload",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "ok",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "Boolean",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/session-chat.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "Viewer",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "claudeApiKeyConfigured",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "Boolean",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "user",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "AuthUser",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/viewer.ts",
        block: true,
      },
    },
    {
      kind: "InputObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "CreateSessionInput",
      },
      fields: [
        {
          kind: "InputValueDefinition",
          name: {
            kind: "Name",
            value: "name",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "InputValueDefinition",
          name: {
            kind: "Name",
            value: "repoRef",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "InputValueDefinition",
          name: {
            kind: "Name",
            value: "repoUrl",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/session.ts",
        block: true,
      },
    },
    {
      kind: "InputObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "ExecuteSessionInput",
      },
      fields: [
        {
          kind: "InputValueDefinition",
          name: {
            kind: "Name",
            value: "cmd",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "InputValueDefinition",
          name: {
            kind: "Name",
            value: "cwd",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "InputValueDefinition",
          name: {
            kind: "Name",
            value: "pty",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "Boolean",
            },
          },
        },
        {
          kind: "InputValueDefinition",
          name: {
            kind: "Name",
            value: "sessionId",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "ID",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/session.ts",
        block: true,
      },
    },
    {
      kind: "InputObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "SaveClaudeApiKeyInput",
      },
      fields: [
        {
          kind: "InputValueDefinition",
          name: {
            kind: "Name",
            value: "apiKey",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/viewer.ts",
        block: true,
      },
    },
    {
      kind: "InputObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "SendSessionChatMessageInput",
      },
      fields: [
        {
          kind: "InputValueDefinition",
          name: {
            kind: "Name",
            value: "cwd",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "InputValueDefinition",
          name: {
            kind: "Name",
            value: "maxTurns",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "Int",
            },
          },
        },
        {
          kind: "InputValueDefinition",
          name: {
            kind: "Name",
            value: "prompt",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "InputValueDefinition",
          name: {
            kind: "Name",
            value: "sessionId",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "ID",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/session-chat.ts",
        block: true,
      },
    },
    {
      kind: "InputObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "SubmitSessionChatUserInputAnswerInput",
      },
      fields: [
        {
          kind: "InputValueDefinition",
          name: {
            kind: "Name",
            value: "key",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "InputValueDefinition",
          name: {
            kind: "Name",
            value: "values",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "ListType",
              type: {
                kind: "NonNullType",
                type: {
                  kind: "NamedType",
                  name: {
                    kind: "Name",
                    value: "String",
                  },
                },
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/session-chat.ts",
        block: true,
      },
    },
    {
      kind: "InputObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "SubmitSessionChatUserInputInput",
      },
      fields: [
        {
          kind: "InputValueDefinition",
          name: {
            kind: "Name",
            value: "answers",
          },
          type: {
            kind: "ListType",
            type: {
              kind: "NonNullType",
              type: {
                kind: "NamedType",
                name: {
                  kind: "Name",
                  value: "SubmitSessionChatUserInputAnswerInput",
                },
              },
            },
          },
        },
        {
          kind: "InputValueDefinition",
          name: {
            kind: "Name",
            value: "behavior",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "SubmitSessionChatUserInputBehaviorInput",
              },
            },
          },
        },
        {
          kind: "InputValueDefinition",
          name: {
            kind: "Name",
            value: "message",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "InputValueDefinition",
          name: {
            kind: "Name",
            value: "sessionId",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "ID",
              },
            },
          },
        },
        {
          kind: "InputValueDefinition",
          name: {
            kind: "Name",
            value: "toolUseId",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/session-chat.ts",
        block: true,
      },
    },
    {
      kind: "InputObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "TerminateSessionInput",
      },
      fields: [
        {
          kind: "InputValueDefinition",
          name: {
            kind: "Name",
            value: "sessionId",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "ID",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/server/graphql/schema/session.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeExtension",
      name: {
        kind: "Name",
        value: "Mutation",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "createSession",
          },
          arguments: [
            {
              kind: "InputValueDefinition",
              name: {
                kind: "Name",
                value: "input",
              },
              type: {
                kind: "NonNullType",
                type: {
                  kind: "NamedType",
                  name: {
                    kind: "Name",
                    value: "CreateSessionInput",
                  },
                },
              },
            },
          ],
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "Session",
              },
            },
          },
          description: {
            kind: "StringValue",
            value: "Defined in: src/server/graphql/schema/session.ts",
            block: true,
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "executeSession",
          },
          arguments: [
            {
              kind: "InputValueDefinition",
              name: {
                kind: "Name",
                value: "input",
              },
              type: {
                kind: "NonNullType",
                type: {
                  kind: "NamedType",
                  name: {
                    kind: "Name",
                    value: "ExecuteSessionInput",
                  },
                },
              },
            },
          ],
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "SessionExecResult",
              },
            },
          },
          description: {
            kind: "StringValue",
            value: "Defined in: src/server/graphql/schema/session.ts",
            block: true,
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "saveClaudeApiKey",
          },
          arguments: [
            {
              kind: "InputValueDefinition",
              name: {
                kind: "Name",
                value: "input",
              },
              type: {
                kind: "NonNullType",
                type: {
                  kind: "NamedType",
                  name: {
                    kind: "Name",
                    value: "SaveClaudeApiKeyInput",
                  },
                },
              },
            },
          ],
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "SaveClaudeApiKeyPayload",
              },
            },
          },
          description: {
            kind: "StringValue",
            value: "Defined in: src/server/graphql/schema/viewer.ts",
            block: true,
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "sendSessionChatMessage",
          },
          arguments: [
            {
              kind: "InputValueDefinition",
              name: {
                kind: "Name",
                value: "input",
              },
              type: {
                kind: "NonNullType",
                type: {
                  kind: "NamedType",
                  name: {
                    kind: "Name",
                    value: "SendSessionChatMessageInput",
                  },
                },
              },
            },
          ],
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "SendSessionChatMessagePayload",
              },
            },
          },
          description: {
            kind: "StringValue",
            value: "Defined in: src/server/graphql/schema/session-chat.ts",
            block: true,
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "submitSessionChatUserInput",
          },
          arguments: [
            {
              kind: "InputValueDefinition",
              name: {
                kind: "Name",
                value: "input",
              },
              type: {
                kind: "NonNullType",
                type: {
                  kind: "NamedType",
                  name: {
                    kind: "Name",
                    value: "SubmitSessionChatUserInputInput",
                  },
                },
              },
            },
          ],
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "SubmitSessionChatUserInputPayload",
              },
            },
          },
          description: {
            kind: "StringValue",
            value: "Defined in: src/server/graphql/schema/session-chat.ts",
            block: true,
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "terminateSession",
          },
          arguments: [
            {
              kind: "InputValueDefinition",
              name: {
                kind: "Name",
                value: "input",
              },
              type: {
                kind: "NonNullType",
                type: {
                  kind: "NamedType",
                  name: {
                    kind: "Name",
                    value: "TerminateSessionInput",
                  },
                },
              },
            },
          ],
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "Session",
              },
            },
          },
          description: {
            kind: "StringValue",
            value: "Defined in: src/server/graphql/schema/session.ts",
            block: true,
          },
        },
      ],
    },
    {
      kind: "ObjectTypeExtension",
      name: {
        kind: "Name",
        value: "Query",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "session",
          },
          arguments: [
            {
              kind: "InputValueDefinition",
              name: {
                kind: "Name",
                value: "id",
              },
              type: {
                kind: "NonNullType",
                type: {
                  kind: "NamedType",
                  name: {
                    kind: "Name",
                    value: "ID",
                  },
                },
              },
            },
          ],
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "Session",
            },
          },
          description: {
            kind: "StringValue",
            value: "Defined in: src/server/graphql/schema/session.ts",
            block: true,
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "sessions",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "ListType",
              type: {
                kind: "NonNullType",
                type: {
                  kind: "NamedType",
                  name: {
                    kind: "Name",
                    value: "Session",
                  },
                },
              },
            },
          },
          description: {
            kind: "StringValue",
            value: "Defined in: src/server/graphql/schema/session.ts",
            block: true,
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "viewer",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "Viewer",
            },
          },
          description: {
            kind: "StringValue",
            value: "Defined in: src/server/graphql/schema/viewer.ts",
            block: true,
          },
        },
      ],
    },
    {
      kind: "ObjectTypeExtension",
      name: {
        kind: "Name",
        value: "Session",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "chat",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "SessionChat",
              },
            },
          },
          description: {
            kind: "StringValue",
            value: "Defined in: src/server/graphql/schema/session-chat.ts",
            block: true,
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "ssh",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "SessionSshInfo",
            },
          },
          description: {
            kind: "StringValue",
            value: "Defined in: src/server/graphql/schema/session.ts",
            block: true,
          },
        },
      ],
    },
    {
      kind: "ObjectTypeExtension",
      name: {
        kind: "Name",
        value: "SessionChat",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "pendingUserInput",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "SessionChatPendingUserInputPayload",
            },
          },
          description: {
            kind: "StringValue",
            value: "Defined in: src/server/graphql/schema/session-chat.ts",
            block: true,
          },
        },
      ],
    },
  ],
} as DocumentNode;
